# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  webapp:
    build:
      context: "/home/tiehung/Project/LiteratureInstructionalPlan/BackEnd"
      dockerfile: "Dockerfile"
      target: "build"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "lip.webapp:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "/home/tiehung/Project/LiteratureInstructionalPlan/BackEnd/LIP.WebApp:/app:rw"
    - "/home/tiehung/Project/LiteratureInstructionalPlan/BackEnd:/src:rw"
    - "/home/tiehung/.nuget/packages:/root/.nuget/packages"
    - "/home/tiehung/.local/share/JetBrains/RiderRemoteDebugger/2025.2.4/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/655/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/tiehung/.cache/JetBrains/Rider2025.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_11_07_10_22_33:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
